version: '2'

services:
  react:
    build:
      context: ./docker
    command: yarn start
    working_dir: /app/src 
    tty: true
    environment:
    - LOCAL_USER_ID
    ports:
    - 19000:19000
    - 19002:19002
    volumes:
    - .:/app:delegated

volumes:
  home: